version: '3.7'

services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=upspi
      - MYSQL_PASSWORD=upspi
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
    volumes:
      - ./data/nextcloud:/var/www/html
      # below mapping is for using External Storage (local) to mount samba shared folder into Nextcloud. Change as needed.
      - /home/upspi/Desktop/share/nextcloud_share:/mnt/samba
    environment:
      - MYSQL_PASSWORD=upspi
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db

networks:
  default:
    driver: bridge
